font:
  normal:
    family: Menlo

  size: 13.0

window:
  dimensions:
    columns: 80
    lines: 24

  padding:
    x: 5
    y: 5

mouse:
  hide_when_typing: true

colors:
  primary:
    foreground: '0xabb2bf'
    background: '0x282c34'

  cursor:
    text: '0x2c323c'
    cursor: '0x5c6370'

  selection:
    text: CellForeground
    background: '0x3e4452'

  normal:
    black:   '0x2c323c'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xe5c07b'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0x5c6370'

  bright:
    black:   '0x3e4452'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xe5c07b'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xabb2bf'
