{pkgs, ...}:
with pkgs; {
  environment.systemPackages = lib.flatten (builtins.attrValues {
    coreutils = [
      coreutils-full
      findutils
      findutils.locate
      gnugrep
      gnumake
      gnused
      gnutar
      inetutils
      time
    ];
    scripts = [
      battery
      flushdns
      yabaictl
    ];
    others = [
      _1password
      alejandra
      awscli2
      buf
      cargo
      cargo-watch
      clippy
      cloc
      docker
      fd
      gcc
      go
      gofumpt
      golangci-lint
      gotools
      grc
      highlight
      httpie
      kubectl
      kubectx
      luaPackages.luacheck
      luajit
      mkcert
      neofetch
      nodePackages.eslint
      nodePackages.prettier
      nodejs
      parallel
      python3
      python3Packages.autopep8
      python3Packages.flake8
      python3Packages.isort
      ripgrep
      rustc
      rustfmt
      sd
      shellcheck
      shfmt
      silver-searcher
      sqlfluff
      sshuttle
      statix
      stylua
      terraform
      vim-vint
      watch
    ];
  });
}
