call plugins#load()

let mapleader = ' '

let g:onedark_color_overrides = {
\  "background": {
\    "gui": "#000000",
\    "cterm": "NONE",
\    "cterm16": "NONE"
\  },
\  "black": {
\    "gui": "#000000",
\    "cterm": "NONE",
\    "cterm16": "NONE"
\  }
\}

colorscheme onedark

set termguicolors
set hidden
set backup
set swapfile
set undofile
set backupdir=$XDG_DATA_HOME/vim/backup//
set directory=$XDG_DATA_HOME/vim/swap//
set undodir=$XDG_DATA_HOME/vim/undo//
set shortmess-=S
set shortmess+=FIc
set updatetime=100
set signcolumn=yes
set lazyredraw
set number
set relativenumber
set smartindent
set cursorline
set mouse=a
set clipboard=unnamed
set splitbelow
set splitright
set ignorecase
set smartcase
set incsearch
set hlsearch
set expandtab
set shiftwidth=2
set tabstop=2
set softtabstop=2
set smarttab
set showcmd
