{ pkgs, ... }:

let
  coreutils = [
    pkgs.coreutils-full
    pkgs.findutils
    pkgs.findutils.locate
    pkgs.gnugrep
    pkgs.gnumake
    pkgs.gnused
    pkgs.gnutar
    pkgs.inetutils
    pkgs.time
  ];
in
{
  environment.systemPackages = coreutils ++ [
    pkgs._1password
    pkgs.awscli2
    pkgs.buf
    pkgs.docker
    pkgs.fd
    pkgs.go
    pkgs.gofumpt
    pkgs.golangci-lint
    pkgs.gotools
    pkgs.httpie
    pkgs.kubectl
    pkgs.luaPackages.luacheck
    pkgs.mkcert
    pkgs.neofetch
    pkgs.nixpkgs-fmt
    pkgs.nodePackages.eslint
    pkgs.nodePackages.prettier
    pkgs.nodejs
    pkgs.ranger
    pkgs.ripgrep
    pkgs.rustup
    pkgs.sd
    pkgs.shellcheck
    pkgs.shfmt
    pkgs.silver-searcher
    pkgs.sqlfluff
    pkgs.sshuttle
    pkgs.statix
    pkgs.stylua
    pkgs.terraform
    pkgs.vim-vint
    pkgs.watch
  ];
}
