local lspconfig = require("lspconfig")

lspconfig.lua_ls.setup({
	on_attach = function(client, bufnr)
		vim.keymap.set("n", "<LocalLeader>K", vim.lsp.buf.signature_help)
		vim.keymap.set("n", "<LocalLeader>[d", vim.diagnostic.goto_prev)
		vim.keymap.set("n", "<LocalLeader>]d", vim.diagnostic.goto_next)
		vim.keymap.set("n", "<LocalLeader>e", vim.diagnostic.open_float)
		vim.keymap.set("n", "<LocalLeader>f", function() vim.lsp.buf.format({ async = true }) end)
		vim.keymap.set("n", "<LocalLeader>gD", vim.lsp.buf.declaration)
		vim.keymap.set("n", "<LocalLeader>gd", vim.lsp.buf.definition)
		vim.keymap.set("n", "<LocalLeader>gi", vim.lsp.buf.implementation)
		vim.keymap.set("n", "<LocalLeader>go", vim.lsp.buf.type_definition)
		vim.keymap.set("n", "<LocalLeader>gr", vim.lsp.buf.references)
		vim.keymap.set("n", "<LocalLeader>k", vim.lsp.buf.hover)
		vim.keymap.set("n", "<LocalLeader>q", vim.diagnostic.setloclist)
		vim.keymap.set("n", "<LocalLeader>rn", vim.lsp.buf.rename)
		vim.keymap.set("n", "<LocalLeader>wa", vim.lsp.buf.add_workspace_folder)
		vim.keymap.set("n", "<LocalLeader>wl", function() print(vim.inspect(vim.lsp.buf.list_workspace_folders())) end)
		vim.keymap.set("n", "<LocalLeader>wr", vim.lsp.buf.remove_workspace_folder)
		vim.keymap.set({ "n", "x" }, "<LocalLeader>ca", vim.lsp.buf.code_action)
	end,
})
